from django.conf.urls import patterns, url

urlpatterns = patterns('',
   url(r'^$', 'sitemngr.views.index'),
   url(r'^viewall/', 'sitemngr.views.viewall'),
   url(r'^add/', 'sitemngr.views.add'),
   url(r'^viewsite/(\d+)', 'sitemngr.views.viewsite'),
   url(r'^editsite/(\d+)', 'sitemngr.views.editsite'),
   url(r'^addsite/', 'sitemngr.views.addsite'),
   url(r'^viewwormhole/(\d+)', 'sitemngr.views.viewwormhole'),
   url(r'^editwormhole/(\d+)', 'sitemngr.views.editwormhole'),
   url(r'^addwormhole/', 'sitemngr.views.addwormhole'),
   url(r'^recentscanedits/', 'sitemngr.views.recentscanedits'),
   url(r'^paste/', 'sitemngr.views.paste'),
   url(r'^system/([-a-zA-Z0-9 ]+)', 'sitemngr.views.system'),
   url(r'^system/', 'sitemngr.views.systemlanding'),
   url(r'^lookup/(\w+)', 'sitemngr.views.lookup'),
   url(r'^igbtest/', 'sitemngr.views.igbtest'),
   url(r'^output/', 'sitemngr.views.output'),
   url(r'^help/', 'sitemngr.views.viewhelp'),
   url(r'^mastertable/', 'sitemngr.views.mastertable'),
   url(r'^changelog/', 'sitemngr.views.changelog'),
   url(r'^checkkills/', 'sitemngr.views.checkkills'),
   url(r'^stats/', 'sitemngr.views.stats'),
   url(r'^settings/', 'sitemngr.views.settings'),
   url(r'^login/', 'sitemngr.views.login_page'),
   url(r'^logout/', 'sitemngr.views.logout_page'),
   url(r'^create_account/', 'sitemngr.views.create_account'),
   url(r'^overlay/', 'sitemngr.views.overlay'),
   url(r'^get_tradehub_jumps/([-a-zA-Z0-9 ]+)', 'sitemngr.views.get_tradehub_jumps'),
   url(r'^get_search_results/([-a-zA-Z0-9 ]+)/([-a-zA-Z0-9_]+)', 'sitemngr.views.get_search_results')
)
