from django.conf.urls import patterns, url

urlpatterns = patterns('',
   url(r'^$', 'sitemngr.views.index'),
   url(r'^viewall/', 'sitemngr.views.viewall'),
   url(r'^add/', 'sitemngr.views.add'),
   url(r'^viewsite/(\d+)', 'sitemngr.views.viewsite'),
   url(r'^editsite/(\d+)', 'sitemngr.views.editsite'),
   url(r'^addsite/', 'sitemngr.views.addsite'),
   url(r'^viewwormhole/(\d+)', 'sitemngr.views.viewwormhole'),
   url(r'^editwormhole/(\d+)', 'sitemngr.views.editwormhole'),
   url(r'^addwormhole/', 'sitemngr.views.addwormhole'),
   url(r'^recentscanedits/', 'sitemngr.views.recentscanedits'),
   url(r'^paste/', 'sitemngr.views.paste'),
   url(r'^system/(\w+)', 'sitemngr.views.system'),
   url(r'^system/', 'sitemngr.views.systemlanding'),
   url(r'^lookup/(\w+)', 'sitemngr.views.lookup'),
   url(r'^igbtest/', 'sitemngr.views.igbtest'),
   url(r'^output/', 'sitemngr.views.output'),
   url(r'^help/', 'sitemngr.views.viewhelp'),
   url(r'^mastertable/', 'sitemngr.views.mastertable'),
   url(r'^changelog/', 'sitemngr.views.changelog'),
   url(r'^checkkills/', 'sitemngr.views.checkkills'),
   url(r'^stats/', 'sitemngr.views.stats'),
   url(r'^settings/', 'sitemngr.views.settings'),
   url(r'^whitelist/request/', 'sitemngr.views.requestwhitelist'),
   # url(r'^chains/', 'sitemngr.views.chains'),
   # url(r'^PLACE', 'sitemngr.views.PAGE'),
)
